module Runivedo
  module Protocol
    PROTOCOL_VERSION = 1

    OPERATION_CALL_ROM = 1
    OPERATION_ANSWER_CALL = 2
    OPERATION_NOTIFY = 3
    OPERATION_INSTANCIATE = 4
    OPERATION_DELETE = 5

    DOORKEEPER_UUID = "23D84DC0-254A-4737-9D8B-3C789A050409"
    UROLOGIN_NAME = "urologin"
  end
end
